/*OpenGL Libraries*/
#include <glut.h>
/*Standard Libraries*/
#include <iostream>
/*Basic Libraries*/
#include <ctime>
#include <fstream>
#include <vector>
#include <math.h>
#include <string>
#include <sstream>
#include <time.h>
#include <algorithm>